name: Tests
on: push

jobs:
  verify:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 localhost.firebaseio.test" | sudo tee -a /etc/hosts
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
